import type { AuditTrailEntry } from "@/types/auditTrail";

export const auditTrailEntries: AuditTrailEntry[] = [
  {
    id: "AT-012",
    date: "Sept 7, 2026",
    time: "10:42 AM",
    staff: "Secretary Reyes",
    module: "Documents",
    action: "Verified request",
    details: "Verified DR-002 for Jose Ramirez, Certificate of Residency",
  },
  {
    id: "AT-011",
    date: "Sept 7, 2026",
    time: "9:15 AM",
    staff: "Secretary Reyes",
    module: "Events",
    action: "Posted event",
    details: "Posted Clean-up Drive and assigned Kagawad Dela Cruz",
  },
  {
    id: "AT-010",
    date: "Sept 6, 2026",
    time: "4:20 PM",
    staff: "Secretary Reyes",
    module: "Documents",
    action: "Marked as done",
    details: "Marked DR-004 as done. Carlo Mendoza may now pick up the clearance",
  },
  {
    id: "AT-009",
    date: "Sept 6, 2026",
    time: "2:05 PM",
    staff: "Secretary Reyes",
    module: "Documents",
    action: "Marked as picked up",
    details: "Resident Liza Navarro claimed Certificate of Indigency DR-005",
  },
  {
    id: "AT-008",
    date: "Sept 6, 2026",
    time: "11:30 AM",
    staff: "Secretary Reyes",
    module: "Residents",
    action: "Registered resident",
    details: "Added Ana Villanueva of Purok 1, Centro to the registry",
  },
  {
    id: "AT-007",
    date: "Sept 5, 2026",
    time: "3:48 PM",
    staff: "Secretary Reyes",
    module: "Events",
    action: "Updated event",
    details: "Changed Health Mission time and assigned Nurse Bautista",
  },
  {
    id: "AT-006",
    date: "Sept 5, 2026",
    time: "8:12 AM",
    staff: "Secretary Reyes",
    module: "Documents",
    action: "Verified request",
    details: "Verified DR-004 for Carlo Mendoza, Barangay Clearance",
  },
];
