import type { BarangayEvent } from "@/types/event";

export const initialEvents: BarangayEvent[] = [
  {
    id: "EV-001",
    title: "Rice and grocery pack release",
    description: "Rice and grocery packs will be given to listed households. Bring a valid barangay record.",
    type: "Relief Goods Distribution",
    audience: "All",
    assignee: "Secretary Reyes",
    location: "Barangay Hall",
    date: "2026-09-10",
    time: "09:00",
  },
  {
    id: "EV-002",
    title: "Inter-purok basketball cup",
    description: "Open basketball games for registered players. Teams should sign in before the first game.",
    type: "Barangay Tournament",
    audience: "All",
    assignee: "SK Chairperson Cruz",
    location: "Barangay Covered Court",
    date: "2026-09-20",
    time: "14:00",
  },
  {
    id: "EV-003",
    title: "Coastal and street clean-up",
    description: "Join the morning clean-up along the riverside and nearby streets. Tools will be provided.",
    type: "Clean-up Drive",
    audience: "Fisherman",
    assignee: "Kagawad Dela Cruz",
    location: "Purok 4, Riverside",
    date: "2026-09-05",
    time: "07:00",
  },
  {
    id: "EV-004",
    title: "Free check-up and medicine",
    description: "Free basic check-up and available medicine for residents who need medical help.",
    type: "Medical Mission",
    audience: "All",
    assignee: "Nurse Bautista",
    location: "Barangay Plaza",
    date: "2026-09-18",
    time: "08:30",
  },
];
