import type { Resident } from "@/types/resident";

export const initialResidents: Resident[] = [
  {
    id: "RS-001",
    name: "Maria Santos",
    age: 28,
    sex: "Female",
    civilStatus: "Single",
    birthDate: "March 12, 1998",
    address: "Purok 2, Sitio Maligaya",
    contact: "0917 555 2101",
    dateFiled: "Sept. 8, 2026",
    status: "Pending",
    nationalIdFront: "/residents/id-front.svg",
    nationalIdBack: "/residents/id-back.svg",
    declineReason: null,
  },
  {
    id: "RS-002",
    name: "Jose Ramirez",
    age: 19,
    sex: "Male",
    civilStatus: "Single",
    birthDate: "July 3, 2007",
    address: "Purok 4, Riverside",
    contact: "0918 442 1188",
    dateFiled: "Sept. 7, 2026",
    status: "Pending",
    nationalIdFront: "/residents/id-front.svg",
    nationalIdBack: "/residents/id-back.svg",
    declineReason: null,
  },
  {
    id: "RS-003",
    name: "Ana Villanueva",
    age: 41,
    sex: "Female",
    civilStatus: "Married",
    birthDate: "November 21, 1984",
    address: "Purok 1, Centro",
    contact: "0922 300 7745",
    dateFiled: "Sept. 6, 2026",
    status: "Registered",
    nationalIdFront: "/residents/id-front.svg",
    nationalIdBack: "/residents/id-back.svg",
    declineReason: null,
  },
  {
    id: "RS-004",
    name: "Carlo Mendoza",
    age: 35,
    sex: "Male",
    civilStatus: "Married",
    birthDate: "January 8, 1991",
    address: "Purok 5, San Isidro",
    contact: "0916 889 3340",
    dateFiled: "Sept. 5, 2026",
    status: "Registered",
    nationalIdFront: "/residents/id-front.svg",
    nationalIdBack: "/residents/id-back.svg",
    declineReason: null,
  },
  {
    id: "RS-005",
    name: "Liza Navarro",
    age: 22,
    sex: "Female",
    civilStatus: "Single",
    birthDate: "May 16, 2004",
    address: "Purok 3, Hillside",
    contact: "0908 221 6672",
    dateFiled: "Sept. 4, 2026",
    status: "Not registered",
    nationalIdFront: "/residents/id-front.svg",
    nationalIdBack: "/residents/id-back.svg",
    declineReason: "Not a resident of this barangay",
  },
];
